version: '3'
services:
  checkin-db:
    build: ./checkin-db
    image: checkin-db:1.0
    volumes:
      - checkin-data:/data/db
    networks:
      - checkin-net
  checkin-api:
    build: ./checkin-api
    image: checkin-api:1.0
    depends_on:
      - checkin-db
    volumes:
      - ./checkin-api/:/usr/local/app
    networks:
      - checkin-net
    ports:
      - 8000:8000
  checkin-client:
    build: ./checkin-client
    image: checkin-client:1.0
    volumes:
      - ./checkin-client/dist:/usr/share/nginx/html
    networks:
      - checkin-net
    ports:
      - 80:80
networks:
  checkin-net:
volumes:
  checkin-data:
